export const ORDER_DETAILS_FETCH = "ORDER_DETAILS_FETCH";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_ERROR = "ORDER_DETAILS_ERROR";
export const ORDER_ITEMS_MODAL_TOGGLE = "ORDER_ITEMS_MODAL_TOGGLE";
export const ORDER_ITEMS_FETCH = "ORDER_ITEMS_FETCH";