export const FETCH_ORDER_DETAILS = "FETCH_ORDER_DETAILS";
export const RECEIVE_ORDER_DETAILS = "RECEIVE_ORDER_DETAILS";
export const FAIL_ORDER_DETAILS = "FAIL_ORDER_DETAILS";
export const TOGGLE_ORDER_ITEMS = "TOGGLE_ORDER_ITEMS";
export const FETCH_ORDER_ITEMS = "FETCH_ORDER_ITEMS";